//data.c
#include "header.h"
char pcechar[] = ".PNBRQKpnbrqk";
char sidechar[] = "wb-";
char rankchar[] = "12345678";
char filechar[] = "abcdefgh";

int piecebig[13] = {FALSE, FALSE,TRUE,TRUE,TRUE,TRUE,TRUE,FALSE,TRUE,TRUE,TRUE,TRUE,TRUE};
int piecemaj[13] = {FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE,FALSE,FALSE,FALSE,TRUE,TRUE,TRUE};
int piecemin[13] = {FALSE, FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE};
int pieceval[13] = {0,100,325,325,550,1000,50000,100,325,325,550,1000,50000};
int piececol[13] = {BOTH,WHITE,WHITE,WHITE,WHITE,WHITE,WHITE,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK};

int pieceknight[13] ={FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE};
int pieceking[13] ={FALSE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE,FALSE,FALSE,FALSE,FALSE,FALSE,TRUE};
int piecerookqueen[13] ={FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE,FALSE,FALSE,FALSE,TRUE,TRUE,FALSE};
int piecebishopqueen[13] = {FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,FALSE,FALSE,FALSE,TRUE,FALSE,TRUE,FALSE};

